# syntax=docker/dockerfile:1
FROM node:lts-alpine

#secrets
ARG NODE_ENV
ENV NODE_ENV ${NODE_ENV}

ARG PGHOST
ENV PGHOST ${PGHOST}

ARG PGPORT
ENV PGPORT ${PGPORT}

ARG PGDATABASE
ENV PGDATABASE ${PGDATABASE}

ARG PGUSER
ENV PGUSER ${PGUSER}

ARG PGPASSWORD
ENV PGPASSWORD ${PGPASSWORD}

ARG MAILUSER
ENV MAILUSER ${MAILUSER}

ARG MAILPASS
ENV MAILPASS ${MAILPASS}
  
ARG SECRETKEY
ENV SECRETKEY ${SECRETKEY}

ARG LOGS_HOST
ENV LOGS_HOST ${LOGS_HOST}

ARG LOGS_PORT
ENV LOGS_PORT ${LOGS_PORT}

ARG LOGS_USER
ENV LOGS_USER ${LOGS_USER}

ARG LOGS_PASSWORD
ENV LOGS_PASSWORD ${LOGS_PASSWORD}

ARG LOGS_DATABASE
ENV LOGS_DATABASE ${LOGS_DATABASE}

WORKDIR /usr/app
COPY package*.json ./
RUN npm install --only=production
COPY . .
EXPOSE 4000
CMD ["npm", "run", "prod"]