# syntax=docker/dockerfile:1
FROM node:lts-alpine
LABEL service="clipr-auth"

RUN apk add --no-cache curl

#secrets
ARG NODE_ENV
ENV NODE_ENV ${NODE_ENV}

ARG APP_NAME
ENV APP_NAME ${APP_NAME}

ARG PGHOST
ENV PGHOST ${PGHOST}

ARG PGHOST2
ENV PGHOST2 ${PGHOST2}

ARG PGHOST3
ENV PGHOST3 ${PGHOST3}

ARG PGPORT
ENV PGPORT ${PGPORT}

ARG PGDATABASE
ENV PGDATABASE ${PGDATABASE}

ARG PGUSER
ENV PGUSER ${PGUSER}

ARG PGPASSWORD
ENV PGPASSWORD ${PGPASSWORD}

ARG MAILUSER
ENV MAILUSER ${MAILUSER}

ARG MAILPASS
ENV MAILPASS ${MAILPASS}
  
ARG SECRETKEY
ENV SECRETKEY ${SECRETKEY}

ARG LOGS_HOST
ENV LOGS_HOST ${LOGS_HOST}

ARG GRAFANA_AUTH
ENV GRAFANA_AUTH ${GRAFANA_AUTH}

WORKDIR /usr/app
COPY package*.json ./
RUN npm install pm2 -g && npm install --only=production
COPY . .
EXPOSE 4000
CMD ["pm2-runtime", "pm2.config.js"]

HEALTHCHECK --interval=10s --timeout=5s --start-period=5s --retries=2 \
  CMD curl -f http://localhost:4000/up || exit 1