# syntax=docker/dockerfile:1
FROM node:lts-alpine

#secrets
ARG NODE_ENV
ENV NODE_ENV ${NODE_ENV}

ARG PGHOST
ENV PGHOST ${PGHOST}

ARG PGPORT
ENV PGPORT ${PGPORT}

ARG PGDATABASE
ENV PGDATABASE ${PGDATABASE}

ARG PGUSER
ENV PGUSER ${PGUSER}

ARG PGPASSWORD
ENV PGPASSWORD ${PGPASSWORD}

ARG MAILUSER
ENV MAILUSER ${MAILUSER}

ARG MAILPASS
ENV MAILPASS ${MAILPASS}
  
ARG SECRETKEY
ENV SECRETKEY ${SECRETKEY}

WORKDIR /usr/app
COPY package*.json ./
RUN npm install --only=production
COPY . .
EXPOSE 4000
CMD ["npm", "run", "prod"]