service: clipr-auth
frameworkVersion: '3'

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  architecture: arm64
  stage: "production"
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    PGHOST: ${self:custom.secrets.PGHOST}
    PGPORT: ${self:custom.secrets.PGPORT}
    PGDATABASE: ${self:custom.secrets.PGDATABASE}
    PGUSER: ${self:custom.secrets.PGUSER}
    PGPASSWORD: ${self:custom.secrets.PGPASSWORD}
    MAILUSER: ${self:custom.secrets.MAILUSER}
    MAILPASS: ${self:custom.secrets.MAILPASS}
    SECRETKEY: ${self:custom.secrets.SECRETKEY}
    LOGHOST: ${self:custom.secrets.LOGHOST}
    LOGPORT: ${self:custom.secrets.LOGPORT}
    LOGDATABASE: ${self:custom.secrets.LOGDATABASE}
    LOGUSER: ${self:custom.secrets.LOGUSER}
    LOGPASSWORD: ${self:custom.secrets.LOGPASSWORD}

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline