name: Deploy main branch
concurrency:
  group: production
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  # or manually
  workflow_dispatch:
    
# Required for secrets.GITHUB_TOKEN
permissions:
  packages: write
  contents: read

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Push to Github Container Repository
      uses: Clipr-Group/ghcr-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        build-args: |
          "NODE_ENV=${{ secrets.NODE_ENV }}"
          "APP_NAME=${{ secrets.APP_NAME }}"
          "PGHOST=${{ secrets.PGHOST }}"
          "PGPORT=${{ secrets.PGPORT }}"
          "PGDATABASE=${{ secrets.PGDATABASE }}"
          "PGUSER=${{ secrets.PGUSER }}"
          "PGPASSWORD=${{ secrets.PGPASSWORD }}"
          "MAILUSER=${{ secrets.MAILUSER }}"
          "MAILPASS=${{ secrets.MAILPASS }}"
          "SECRETKEY=${{ secrets.SECRETKEY }}"
          "LOGS_HOST=${{ secrets.LOGS_HOST }}"
          "GRAFANA_AUTH=${{ secrets.GRAFANA_AUTH }}"
        platforms: linux/amd64,linux/arm64
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
        bundler-cache: true
    - name: Install Kamal
      run: gem install kamal
    - name: Connect to Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
        tags: tag:ci
    - name: release kamal lock
      run: kamal lock release
    - name: Run deploy command
      run: kamal deploy -P -v --version latest
    