name: Deploy main branch

on:
  push:
    branches:
      - main

# Required for secrets.GITHUB_TOKEN
permissions:
  packages: write
  contents: read

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Push to Github Container Repository
      uses: Clipr-Group/ghcr-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        build-args: |
          "NODE_ENV=${{ secrets.NODE_ENV }}"
          "PGHOST=${{ secrets.PGHOST }}"
          "PGPORT=${{ secrets.PGPORT }}"
          "PGDATABASE=${{ secrets.PGDATABASE }}"
          "PGUSER=${{ secrets.PGUSER }}"
          "PGPASSWORD=${{ secrets.PGPASSWORD }}"
          "MAILUSER=${{ secrets.MAILUSER }}"
          "MAILPASS=${{ secrets.MAILPASS }}"
          "SECRETKEY=${{ secrets.SECRETKEY }}"
          "LOGS_HOST=${{ secrets.LOGS_HOST }}"
          "LOGS_PORT=${{ secrets.LOGS_PORT }}"
          "LOGS_USER=${{ secrets.LOGS_USER }}"
          "LOGS_PASSWORD=${{ secrets.LOGS_PASSWORD }}"
          "LOGS_DATABASE=${{ secrets.LOGS_DATABASE }}"
          
    - name: DigitalOcean App Deployment Action
      uses: rdarida/digitalocean-app-deployment-action@v1.0.2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        appId: ${{ secrets.DIGITALOCEAN_APP_ID }}
